name: Enforce Branch Flow
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate base/head
        run: |
          BASE="${{ github.base_ref }}"
          HEAD="${{ github.head_ref }}"
          if { [ "$BASE" = "integration" ] && [ "$HEAD" = "main" ]; } || \
             { [ "$BASE" = "production" ] && [ "$HEAD" = "integration" ]; }; then
            exit 0
          fi
          echo "::error ::Invalid flow. Allowed: main→integration, integration→production."
          exit 1
